export const DLH_COURSES = [
  // ─── Computer & IT Fundamentals (5 courses) ───
  {
    id: "computer-appreciation",
    title: "Computer Appreciation",
    category: "Computer & IT Fundamentals",
    description: "Introduction to computers, hardware components, software basics, and how computers work in everyday life.",
    image_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400",
    topics: ["Computer Hardware", "Software Basics", "Input & Output Devices", "Storage Devices", "Operating Systems Intro", "Computer History"],
  },
  {
    id: "digital-literacy",
    title: "Digital Literacy",
    category: "Computer & IT Fundamentals",
    description: "Build essential digital skills for navigating the modern world: online research, digital communication, and safe internet use.",
    image_url: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400",
    topics: ["Online Research", "Digital Communication", "Social Media Basics", "Online Safety", "Digital Citizenship", "Information Evaluation"],
  },
  {
    id: "ict-fundamentals",
    title: "ICT Fundamentals",
    category: "Computer & IT Fundamentals",
    description: "Core Information and Communication Technology concepts, terminology, and applications for beginners.",
    image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400",
    topics: ["ICT Concepts", "Networking Basics", "Internet Fundamentals", "Software Applications", "Data Representation", "ICT in Society"],
  },
  {
    id: "operating-systems",
    title: "Operating Systems (Windows, macOS, Linux)",
    category: "Computer & IT Fundamentals",
    description: "Understand and navigate Windows, macOS, and Linux operating systems for personal and professional use.",
    image_url: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=400",
    topics: ["Windows Navigation", "macOS Basics", "Linux Introduction", "File Management", "System Settings", "Software Installation"],
  },
  {
    id: "internet-email",
    title: "Internet & Email Essentials",
    category: "Computer & IT Fundamentals",
    description: "Master internet browsing, search engines, email setup, professional email writing, and online tools.",
    image_url: "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=400",
    topics: ["Web Browsing", "Search Engines", "Email Setup", "Professional Email Writing", "Online Tools", "Internet Security"],
  },

  // ─── Microsoft Office Suite (7 courses) ───
  {
    id: "ms-word",
    title: "Microsoft Word",
    category: "Microsoft Office Suite",
    description: "Master document creation, formatting, tables, headers, mail merge, templates, and professional report writing.",
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    topics: ["Document Formatting", "Tables & Charts", "Headers & Footers", "Mail Merge", "Templates", "Report Writing"],
  },
  {
    id: "ms-excel",
    title: "Microsoft Excel (Beginner → Advanced)",
    category: "Microsoft Office Suite",
    description: "Learn spreadsheets, formulas, pivot tables, charts, data analysis, VLOOKUP, and financial modeling.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["Formulas & Functions", "Pivot Tables", "Charts & Graphs", "Data Analysis", "VLOOKUP & HLOOKUP", "Financial Modeling"],
  },
  {
    id: "ms-powerpoint",
    title: "Microsoft PowerPoint",
    category: "Microsoft Office Suite",
    description: "Create stunning presentations with animations, slide design, storytelling, templates, and professional delivery.",
    image_url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400",
    topics: ["Slide Design", "Animations & Transitions", "Storytelling", "Templates", "Presenter Mode", "Professional Tips"],
  },
  {
    id: "ms-access",
    title: "Microsoft Access",
    category: "Microsoft Office Suite",
    description: "Build and manage databases, create forms, queries, reports, and data entry systems using Microsoft Access.",
    image_url: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400",
    topics: ["Database Design", "Forms", "Queries", "Reports", "Data Entry", "Relationships"],
  },
  {
    id: "ms-outlook",
    title: "Microsoft Outlook",
    category: "Microsoft Office Suite",
    description: "Master professional email communication, calendar management, task tracking, and contact organization.",
    image_url: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400",
    topics: ["Email Etiquette", "Calendar Management", "Task Tracking", "Contact Organization", "Rules & Filters", "Meeting Scheduling"],
  },
  {
    id: "ms-onenote",
    title: "Microsoft OneNote",
    category: "Microsoft Office Suite",
    description: "Organize notes, study materials, research, and projects using OneNote for academic and professional use.",
    image_url: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400",
    topics: ["Note Organization", "Notebooks & Sections", "Tags & Search", "Audio Notes", "Collaboration", "Study Templates"],
  },
  {
    id: "ms-publisher",
    title: "Microsoft Publisher",
    category: "Microsoft Office Suite",
    description: "Create professional publications: newsletters, brochures, flyers, business cards, and marketing materials.",
    image_url: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    topics: ["Newsletter Design", "Brochure Creation", "Business Cards", "Flyer Design", "Templates", "Print-Ready Output"],
  },

  // ─── Microsoft Cloud & Enterprise (6 courses) ───
  {
    id: "ms-365-admin",
    title: "Microsoft 365 Administration",
    category: "Microsoft Cloud & Enterprise",
    description: "Administer Microsoft 365 environments: user management, licensing, security, and compliance configurations.",
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400",
    topics: ["User Management", "Licensing", "Security Settings", "Compliance", "Admin Center", "Troubleshooting"],
  },
  {
    id: "ms-teams",
    title: "Microsoft Teams",
    category: "Microsoft Cloud & Enterprise",
    description: "Master virtual meetings, team collaboration, file sharing, channels, and productivity workflows.",
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400",
    topics: ["Virtual Meetings", "Channels & Chats", "File Sharing", "Screen Sharing", "Breakout Rooms", "Integration Apps"],
  },
  {
    id: "sharepoint",
    title: "SharePoint",
    category: "Microsoft Cloud & Enterprise",
    description: "Build intranet sites, document libraries, workflows, and collaboration spaces using SharePoint.",
    image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    topics: ["Site Creation", "Document Libraries", "Workflows", "Permissions", "Lists", "Integration with Teams"],
  },
  {
    id: "onedrive",
    title: "OneDrive",
    category: "Microsoft Cloud & Enterprise",
    description: "Master cloud storage, file syncing, sharing, collaboration, and backup strategies with OneDrive.",
    image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    topics: ["Cloud Storage", "File Syncing", "Sharing & Permissions", "Collaboration", "Backup Strategies", "Mobile Access"],
  },
  {
    id: "power-bi",
    title: "Power BI",
    category: "Microsoft Cloud & Enterprise",
    description: "Create interactive dashboards, reports, and data visualizations to drive business decisions with Power BI.",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    topics: ["Data Import", "Report Building", "Dashboards", "DAX Formulas", "Data Modeling", "Sharing Reports"],
  },
  {
    id: "azure-fundamentals",
    title: "Azure Fundamentals",
    category: "Microsoft Cloud & Enterprise",
    description: "Introduction to Microsoft Azure cloud services, virtual machines, storage, and cloud architecture.",
    image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    topics: ["Azure Overview", "Virtual Machines", "Storage Services", "Networking", "Security", "Pricing & Support"],
  },

  // ─── Digital & Online Skills (9 courses) ───
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    category: "Digital & Online Skills",
    description: "Learn social media strategy, content creation, email marketing, SEO basics, paid ads, and audience growth.",
    image_url: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=400",
    topics: ["Social Media Strategy", "Content Creation", "Email Marketing", "SEO Basics", "Paid Ads", "Audience Growth"],
  },
  {
    id: "social-media-management",
    title: "Social Media Management",
    category: "Digital & Online Skills",
    description: "Master scheduling, analytics, community engagement, influencer partnerships, and brand presence online.",
    image_url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400",
    topics: ["Content Scheduling", "Analytics", "Community Engagement", "Influencer Marketing", "Platform Strategy", "Brand Voice"],
  },
  {
    id: "content-creation",
    title: "Content Creation",
    category: "Digital & Online Skills",
    description: "Create engaging content for social media, blogs, videos, and digital platforms that attract audiences.",
    image_url: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400",
    topics: ["Video Content", "Blog Writing", "Graphic Content", "Viral Strategies", "Content Calendar", "Platform Optimization"],
  },
  {
    id: "seo-mastery",
    title: "SEO (Search Engine Optimization)",
    category: "Digital & Online Skills",
    description: "Deep dive into on-page SEO, off-page SEO, keyword research, link building, and ranking strategies.",
    image_url: "https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=400",
    topics: ["Keyword Research", "On-Page SEO", "Off-Page SEO", "Link Building", "Technical SEO", "Local SEO"],
  },
  {
    id: "email-marketing",
    title: "Email Marketing",
    category: "Digital & Online Skills",
    description: "Build email lists, design campaigns, automate funnels, write compelling copy, and analyze performance.",
    image_url: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400",
    topics: ["List Building", "Campaign Design", "Automation Funnels", "Copywriting", "A/B Testing", "Analytics"],
  },
  {
    id: "online-branding",
    title: "Online Branding",
    category: "Digital & Online Skills",
    description: "Build a powerful brand presence online through consistent messaging, visual identity, and digital storytelling.",
    image_url: "https://images.unsplash.com/photo-1560472355-536de3962603?w=400",
    topics: ["Brand Strategy", "Visual Identity", "Brand Voice", "Digital Storytelling", "Reputation Management", "Brand Consistency"],
  },
  {
    id: "affiliate-marketing",
    title: "Affiliate Marketing",
    category: "Digital & Online Skills",
    description: "Earn commissions by promoting products, building niche websites, and creating passive income streams.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["Affiliate Networks", "Niche Selection", "Content Strategy", "Link Tracking", "Passive Income", "Product Reviews"],
  },
  {
    id: "ecommerce-management",
    title: "E-commerce Management",
    category: "Digital & Online Skills",
    description: "Set up and manage online stores, product listings, payment gateways, logistics, and customer service.",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400",
    topics: ["Store Setup", "Product Listings", "Payment Gateways", "Logistics", "Customer Service", "Sales Strategies"],
  },
  {
    id: "freelancing",
    title: "Freelancing & Remote Work",
    category: "Digital & Online Skills",
    description: "Start freelancing on Upwork, Fiverr, and other platforms. Learn pricing, proposals, and client management.",
    image_url: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400",
    topics: ["Freelance Platforms", "Pricing Strategy", "Writing Proposals", "Client Management", "Time Tracking", "Portfolio Building"],
  },

  // ─── Business Courses (10 courses) ───
  {
    id: "business-management",
    title: "Business Management",
    category: "Business",
    description: "Learn core business management principles: planning, organizing, leading, and controlling business operations.",
    image_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400",
    topics: ["Business Planning", "Operations", "Leadership", "Decision Making", "Business Ethics", "Strategic Management"],
  },
  {
    id: "entrepreneurship",
    title: "Entrepreneurship",
    category: "Business",
    description: "Develop entrepreneurial mindset, identify opportunities, validate ideas, and launch successful ventures.",
    image_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400",
    topics: ["Idea Generation", "Market Research", "Business Models", "Startup Funding", "Lean Startup", "Scaling"],
  },
  {
    id: "small-business-startup",
    title: "Small Business Startup",
    category: "Business",
    description: "Step-by-step guide to starting a small business: registration, funding, operations, and growth strategies.",
    image_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400",
    topics: ["Business Registration", "Funding Sources", "Business Location", "Operations Setup", "Marketing Plan", "Growth Strategy"],
  },
  {
    id: "business-plan-writing",
    title: "Business Plan Writing",
    category: "Business",
    description: "Write professional business plans with executive summaries, financial projections, and market analysis.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Executive Summary", "Market Analysis", "Financial Projections", "Marketing Strategy", "Operations Plan", "Pitch Deck"],
  },
  {
    id: "customer-service",
    title: "Customer Service",
    category: "Business",
    description: "Master customer service skills: communication, conflict resolution, satisfaction measurement, and CRM tools.",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400",
    topics: ["Communication Skills", "Conflict Resolution", "Customer Satisfaction", "CRM Tools", "Phone Etiquette", "Service Excellence"],
  },
  {
    id: "sales-marketing",
    title: "Sales & Marketing",
    category: "Business",
    description: "Learn sales techniques, marketing strategies, lead generation, customer acquisition, and revenue growth.",
    image_url: "https://images.unsplash.com/photo-1553729459-afe8f2e2ed65?w=400",
    topics: ["Sales Techniques", "Lead Generation", "Customer Acquisition", "Marketing Strategy", "Negotiation", "Revenue Growth"],
  },
  {
    id: "financial-accounting",
    title: "Financial Accounting",
    category: "Business",
    description: "Understand accounting principles, financial statements, ledgers, journal entries, and financial reporting.",
    image_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400",
    topics: ["Accounting Principles", "Financial Statements", "Ledgers", "Journal Entries", "Trial Balance", "Financial Reporting"],
  },
  {
    id: "bookkeeping",
    title: "Bookkeeping",
    category: "Business",
    description: "Learn practical bookkeeping: recording transactions, managing accounts, payroll, and tax preparation.",
    image_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400",
    topics: ["Recording Transactions", "Account Management", "Payroll", "Tax Preparation", "Software Tools", "Bank Reconciliation"],
  },
  {
    id: "project-management",
    title: "Project Management",
    category: "Business",
    description: "Learn project planning, task management, Agile basics, team collaboration, and project delivery.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Project Planning", "Task Management", "Agile Basics", "Trello & Asana", "Team Collaboration", "Time Management"],
  },
  {
    id: "hr-management",
    title: "Human Resource Management",
    category: "Business",
    description: "Manage recruitment, employee relations, performance evaluation, training, and organizational development.",
    image_url: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400",
    topics: ["Recruitment", "Employee Relations", "Performance Evaluation", "Training & Development", "HR Policies", "Organizational Development"],
  },

  // ─── Graphic & Visual Design (7 courses) ───
  {
    id: "graphic-design",
    title: "Graphic Design",
    category: "Graphic & Visual Design",
    description: "Master visual design principles, color theory, typography, layout, and creating stunning visual content.",
    image_url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400",
    topics: ["Design Principles", "Color Theory", "Typography", "Layout Design", "Visual Hierarchy", "Portfolio Building"],
  },
  {
    id: "flyer-poster-design",
    title: "Flyer & Poster Design",
    category: "Graphic & Visual Design",
    description: "Create eye-catching flyers and posters for events, businesses, and promotions with professional techniques.",
    image_url: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    topics: ["Layout Techniques", "Color Psychology", "Typography in Posters", "Event Flyers", "Business Posters", "Print Preparation"],
  },
  {
    id: "logo-design",
    title: "Logo Design",
    category: "Graphic & Visual Design",
    description: "Design memorable logos: concept development, sketching, digital creation, and brand mark variations.",
    image_url: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=400",
    topics: ["Logo Concepts", "Sketching", "Digital Creation", "Brand Marks", "Logo Variations", "Client Presentation"],
  },
  {
    id: "branding-visual-identity",
    title: "Branding & Visual Identity",
    category: "Graphic & Visual Design",
    description: "Build complete brand identities: logo systems, color palettes, brand guidelines, and visual storytelling.",
    image_url: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=400",
    topics: ["Brand Strategy", "Color Palettes", "Brand Guidelines", "Visual Storytelling", "Packaging Design", "Brand Audit"],
  },
  {
    id: "ui-ux-design",
    title: "UI/UX Design",
    category: "Graphic & Visual Design",
    description: "Learn wireframing, prototyping, user-centered design, Figma, and creating intuitive user interfaces.",
    image_url: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400",
    topics: ["Wireframing", "Prototyping", "User Research", "Figma", "Visual Hierarchy", "Usability Testing"],
  },
  {
    id: "social-media-design",
    title: "Social Media Design",
    category: "Graphic & Visual Design",
    description: "Create stunning social media graphics: posts, stories, covers, banners, and branded visual content.",
    image_url: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400",
    topics: ["Post Design", "Story Templates", "Cover Images", "Banner Design", "Branded Content", "Platform Dimensions"],
  },
  {
    id: "print-design",
    title: "Print Design",
    category: "Graphic & Visual Design",
    description: "Design professional print materials: business cards, brochures, magazines, banners, and packaging.",
    image_url: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    topics: ["Business Cards", "Brochures", "Magazine Layouts", "Banner Design", "Packaging", "Print-Ready Files"],
  },

  // ─── Design Tools (7 courses) ───
  {
    id: "adobe-photoshop",
    title: "Adobe Photoshop",
    category: "Design Tools",
    description: "Master photo editing, retouching, compositing, digital art, and image manipulation with Photoshop.",
    image_url: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400",
    topics: ["Photo Editing", "Retouching", "Compositing", "Layers & Masks", "Color Correction", "Digital Art"],
  },
  {
    id: "adobe-illustrator",
    title: "Adobe Illustrator",
    category: "Design Tools",
    description: "Create vector graphics, logos, icons, illustrations, and scalable artwork with Adobe Illustrator.",
    image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400",
    topics: ["Vector Graphics", "Pen Tool", "Logo Creation", "Icon Design", "Typography", "Illustration"],
  },
  {
    id: "adobe-indesign",
    title: "Adobe InDesign",
    category: "Design Tools",
    description: "Layout and publish professional documents: magazines, books, brochures, and digital publications.",
    image_url: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    topics: ["Page Layout", "Master Pages", "Typography", "Image Placement", "Print Export", "Digital Publishing"],
  },
  {
    id: "coreldraw",
    title: "CorelDRAW",
    category: "Design Tools",
    description: "Create vector illustrations, logos, signage, and print-ready graphics with CorelDRAW.",
    image_url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400",
    topics: ["Vector Drawing", "Logo Design", "Signage", "Print Graphics", "Color Management", "Effects & Fills"],
  },
  {
    id: "canva",
    title: "Canva",
    category: "Design Tools",
    description: "Design stunning graphics, presentations, social media posts, and marketing materials using Canva.",
    image_url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400",
    topics: ["Templates", "Social Media Graphics", "Presentations", "Brand Kit", "Canva Pro Features", "Animation"],
  },
  {
    id: "pixellab",
    title: "Pixellab",
    category: "Design Tools",
    description: "Create text-based designs, social media graphics, and quick visual content using Pixellab on mobile.",
    image_url: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400",
    topics: ["Text Design", "3D Text", "Social Media Graphics", "Stickers", "Mobile Design", "Quick Editing"],
  },
  {
    id: "figma",
    title: "Figma",
    category: "Design Tools",
    description: "Design user interfaces, prototypes, and collaborative design projects using Figma.",
    image_url: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400",
    topics: ["UI Design", "Prototyping", "Components", "Auto Layout", "Collaboration", "Design Systems"],
  },

  // ─── Web Development (7 courses) ───
  {
    id: "html",
    title: "HTML",
    category: "Web Development",
    description: "Learn the foundation of web development: HTML structure, elements, forms, tables, and semantic markup.",
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    topics: ["HTML Structure", "Elements & Tags", "Forms", "Tables", "Semantic HTML", "Accessibility"],
  },
  {
    id: "css",
    title: "CSS",
    category: "Web Development",
    description: "Style web pages with CSS: layouts, flexbox, grid, animations, responsive design, and modern techniques.",
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    topics: ["Selectors & Properties", "Flexbox", "CSS Grid", "Animations", "Responsive Design", "CSS Variables"],
  },
  {
    id: "javascript",
    title: "JavaScript",
    category: "Web Development",
    description: "Master JavaScript programming: variables, functions, DOM manipulation, events, and modern ES6+ features.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Variables & Types", "Functions", "DOM Manipulation", "Events", "ES6+ Features", "Async Programming"],
  },
  {
    id: "bootstrap",
    title: "Bootstrap",
    category: "Web Development",
    description: "Build responsive websites quickly using Bootstrap's grid system, components, and utility classes.",
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    topics: ["Grid System", "Components", "Utility Classes", "Responsive Breakpoints", "Customization", "Templates"],
  },
  {
    id: "tailwind-css",
    title: "Tailwind CSS",
    category: "Web Development",
    description: "Build modern UIs with Tailwind CSS utility-first framework: responsive design, components, and theming.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Utility Classes", "Responsive Design", "Components", "Dark Mode", "Custom Config", "Plugins"],
  },
  {
    id: "reactjs",
    title: "React.js",
    category: "Web Development",
    description: "Build dynamic web applications with React: components, state, hooks, routing, and modern patterns.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Components", "State & Props", "Hooks", "Routing", "Context API", "Performance"],
  },
  {
    id: "vuejs",
    title: "Vue.js",
    category: "Web Development",
    description: "Create interactive web apps with Vue.js: directives, components, Vuex, Vue Router, and composition API.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Vue Basics", "Components", "Directives", "Vuex", "Vue Router", "Composition API"],
  },

  // ─── Web Platforms (4 courses) ───
  {
    id: "wordpress-dev",
    title: "WordPress Development",
    category: "Web Platforms",
    description: "Build professional websites with WordPress: themes, plugins, WooCommerce, SEO, and site management.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["WordPress Setup", "Themes & Customization", "Plugins", "WooCommerce", "SEO", "Site Management"],
  },
  {
    id: "shopify-dev",
    title: "Shopify Development",
    category: "Web Platforms",
    description: "Build and customize online stores with Shopify: themes, products, payments, and marketing integrations.",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400",
    topics: ["Store Setup", "Theme Customization", "Products & Collections", "Payments", "Marketing", "Analytics"],
  },
  {
    id: "webflow",
    title: "Webflow",
    category: "Web Platforms",
    description: "Design and build responsive websites visually with Webflow's no-code platform and CMS.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["Visual Design", "CMS Setup", "Responsive Design", "Animations", "E-commerce", "Hosting"],
  },
  {
    id: "wix",
    title: "Wix",
    category: "Web Platforms",
    description: "Create professional websites with Wix drag-and-drop builder, templates, and app integrations.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["Drag & Drop Builder", "Templates", "App Market", "SEO Tools", "E-commerce", "Domain Setup"],
  },

  // ─── Programming & Development (5 courses) ───
  {
    id: "software-engineering",
    title: "Software Engineering",
    category: "Software Development",
    description: "Learn software engineering principles: SDLC, design patterns, testing, version control, and best practices.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["SDLC", "Design Patterns", "Testing", "Version Control", "Code Review", "Best Practices"],
  },
  {
    id: "fullstack-dev",
    title: "Full-Stack Development",
    category: "Software Development",
    description: "Master both frontend and backend: React, Node.js, databases, APIs, deployment, and full-stack architecture.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Frontend & Backend", "Node.js", "Databases", "REST APIs", "Deployment", "Architecture"],
  },
  {
    id: "frontend-dev",
    title: "Frontend Development",
    category: "Software Development",
    description: "Specialize in building beautiful, responsive, and accessible user interfaces for the modern web.",
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    topics: ["HTML/CSS/JS", "Responsive Design", "Accessibility", "Frameworks", "Performance", "Testing"],
  },
  {
    id: "backend-dev",
    title: "Backend Development",
    category: "Software Development",
    description: "Build robust server-side applications: APIs, databases, authentication, and server management.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Server-Side Logic", "APIs", "Databases", "Authentication", "Security", "Deployment"],
  },
  {
    id: "mobile-app-dev",
    title: "Mobile App Development",
    category: "Software Development",
    description: "Build mobile applications using React Native, Flutter, and cross-platform development fundamentals.",
    image_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400",
    topics: ["React Native", "Flutter Basics", "Cross-Platform Dev", "App Publishing", "UI Components", "Mobile APIs"],
  },

  // ─── Programming Languages (10 courses) ───
  {
    id: "python-programming",
    title: "Python",
    category: "Programming Languages",
    description: "Learn Python from scratch: syntax, data structures, file handling, automation, and beginner projects.",
    image_url: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400",
    topics: ["Python Basics", "Data Structures", "File Handling", "Automation", "Web Scraping", "Projects"],
  },
  {
    id: "java-programming",
    title: "Java",
    category: "Programming Languages",
    description: "Master Java programming: OOP, data structures, exception handling, and application development.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Java Basics", "OOP", "Data Structures", "Exception Handling", "Collections", "File I/O"],
  },
  {
    id: "javascript-lang",
    title: "JavaScript (Language)",
    category: "Programming Languages",
    description: "Deep dive into JavaScript as a programming language: closures, prototypes, async patterns, and Node.js.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Closures", "Prototypes", "Async/Await", "Node.js", "ES6+ Features", "Design Patterns"],
  },
  {
    id: "php-programming",
    title: "PHP",
    category: "Programming Languages",
    description: "Build dynamic web applications with PHP: forms, databases, sessions, and MVC frameworks like Laravel.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["PHP Basics", "Forms & Validation", "MySQL Integration", "Sessions", "Laravel Intro", "API Development"],
  },
  {
    id: "c-programming",
    title: "C Programming",
    category: "Programming Languages",
    description: "Learn the C programming language: variables, pointers, memory management, and systems programming.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["Variables & Types", "Pointers", "Memory Management", "Functions", "Structs", "File I/O"],
  },
  {
    id: "cpp-programming",
    title: "C++ Programming",
    category: "Programming Languages",
    description: "Master C++ programming: OOP, templates, STL, memory management, and application development.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["C++ Basics", "OOP", "Templates", "STL", "Memory Management", "Projects"],
  },
  {
    id: "csharp-programming",
    title: "C# Programming",
    category: "Programming Languages",
    description: "Learn C# for .NET development: OOP, LINQ, async programming, and building desktop/web applications.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["C# Basics", "OOP", "LINQ", "Async Programming", ".NET Framework", "WinForms/WPF"],
  },
  {
    id: "dart-programming",
    title: "Dart",
    category: "Programming Languages",
    description: "Learn Dart programming language for Flutter development: syntax, OOP, async, and widget building.",
    image_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400",
    topics: ["Dart Syntax", "OOP", "Async Programming", "Collections", "Flutter Integration", "State Management"],
  },
  {
    id: "kotlin-programming",
    title: "Kotlin",
    category: "Programming Languages",
    description: "Master Kotlin for Android development: syntax, coroutines, Jetpack Compose, and modern Android patterns.",
    image_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400",
    topics: ["Kotlin Basics", "Coroutines", "Jetpack Compose", "Android SDK", "Data Classes", "Extensions"],
  },
  {
    id: "swift-programming",
    title: "Swift",
    category: "Programming Languages",
    description: "Learn Swift for iOS development: syntax, SwiftUI, UIKit, data persistence, and publishing to App Store.",
    image_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400",
    topics: ["Swift Basics", "SwiftUI", "UIKit", "Data Persistence", "Networking", "App Store Publishing"],
  },

  // ─── AI & Data (8 courses) ───
  {
    id: "ai-fundamentals",
    title: "Artificial Intelligence Fundamentals",
    category: "AI & Data",
    description: "Introduction to AI concepts, history, applications, ethical considerations, and AI in everyday life.",
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400",
    topics: ["AI Concepts", "History of AI", "Applications", "Ethics", "AI in Daily Life", "Future of AI"],
  },
  {
    id: "machine-learning",
    title: "Machine Learning",
    category: "AI & Data",
    description: "Learn machine learning fundamentals: supervised/unsupervised learning, algorithms, and model evaluation.",
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400",
    topics: ["Supervised Learning", "Unsupervised Learning", "Algorithms", "Model Evaluation", "Feature Engineering", "Scikit-learn"],
  },
  {
    id: "deep-learning",
    title: "Deep Learning",
    category: "AI & Data",
    description: "Explore neural networks, CNNs, RNNs, transfer learning, and deep learning frameworks like TensorFlow.",
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400",
    topics: ["Neural Networks", "CNNs", "RNNs", "Transfer Learning", "TensorFlow", "PyTorch"],
  },
  {
    id: "data-analysis",
    title: "Data Analysis",
    category: "AI & Data",
    description: "Analyze data using spreadsheets, Python, and visualization tools to extract insights and make decisions.",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    topics: ["Data Collection", "Cleaning Data", "Analysis Techniques", "Visualization", "Reporting", "Excel & Python"],
  },
  {
    id: "data-science",
    title: "Data Science",
    category: "AI & Data",
    description: "Master the data science pipeline: data collection, analysis, modeling, visualization, and communication.",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    topics: ["Data Pipeline", "Statistics", "Machine Learning", "Visualization", "Python Libraries", "Communication"],
  },
  {
    id: "big-data",
    title: "Big Data",
    category: "AI & Data",
    description: "Understand big data concepts, Hadoop, Spark, data warehousing, and processing large-scale datasets.",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    topics: ["Big Data Concepts", "Hadoop", "Spark", "Data Warehousing", "ETL", "NoSQL Databases"],
  },
  {
    id: "chatgpt-ai-tools",
    title: "ChatGPT & AI Tools",
    category: "AI & Data",
    description: "Master ChatGPT, AI writing tools, image generators, and productivity AI for work and learning.",
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400",
    topics: ["ChatGPT Mastery", "AI Writing Tools", "Image Generators", "AI Productivity", "AI Automation", "AI Ethics"],
  },
  {
    id: "prompt-engineering",
    title: "Prompt Engineering",
    category: "AI & Data",
    description: "Master writing effective AI prompts for ChatGPT, image generators, and other AI tools.",
    image_url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400",
    topics: ["Prompt Basics", "ChatGPT Prompts", "Image Prompts", "Chain Prompting", "Role Prompting", "Templates"],
  },

  // ─── Cloud & Modern Tech (6 courses) ───
  {
    id: "cloud-computing",
    title: "Cloud Computing",
    category: "Cloud & Modern Tech",
    description: "Introduction to cloud services, deployment models, and cloud-based workflows for businesses.",
    image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    topics: ["Cloud Models", "IaaS/PaaS/SaaS", "Cloud Deployment", "Cloud Security", "Cost Management", "Migration"],
  },
  {
    id: "aws-fundamentals",
    title: "AWS Fundamentals",
    category: "Cloud & Modern Tech",
    description: "Learn Amazon Web Services core services: EC2, S3, Lambda, and cloud architecture fundamentals.",
    image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    topics: ["EC2", "S3 Storage", "Lambda", "IAM", "VPC", "Cloud Architecture"],
  },
  {
    id: "microsoft-azure",
    title: "Microsoft Azure",
    category: "Cloud & Modern Tech",
    description: "Master Azure cloud services: virtual machines, app services, databases, and enterprise solutions.",
    image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    topics: ["Azure Services", "Virtual Machines", "App Services", "Azure SQL", "DevOps", "Security"],
  },
  {
    id: "google-cloud",
    title: "Google Cloud",
    category: "Cloud & Modern Tech",
    description: "Learn Google Cloud Platform services: Compute Engine, Cloud Storage, BigQuery, and AI/ML services.",
    image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    topics: ["Compute Engine", "Cloud Storage", "BigQuery", "AI/ML Services", "Networking", "Security"],
  },
  {
    id: "blockchain",
    title: "Blockchain Technology",
    category: "Cloud & Modern Tech",
    description: "Understand blockchain fundamentals: distributed ledgers, smart contracts, cryptocurrency, and DApps.",
    image_url: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400",
    topics: ["Blockchain Basics", "Distributed Ledgers", "Smart Contracts", "Cryptocurrency", "DApps", "Use Cases"],
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity Fundamentals",
    category: "Cloud & Modern Tech",
    description: "Understand cybersecurity threats, defense strategies, encryption, and protecting digital assets.",
    image_url: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400",
    topics: ["Threat Landscape", "Defense Strategies", "Encryption", "Network Security", "Incident Response", "Compliance"],
  },

  // ─── Networking (7 courses) ───
  {
    id: "computer-networking",
    title: "Computer Networking",
    category: "Networking",
    description: "Learn networking fundamentals: OSI model, TCP/IP, network devices, protocols, and troubleshooting.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["OSI Model", "TCP/IP", "Network Devices", "Protocols", "IP Addressing", "Troubleshooting"],
  },
  {
    id: "network-installation",
    title: "Network Installation",
    category: "Networking",
    description: "Plan, install, and configure network infrastructure: cabling, switches, routers, and access points.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["Cable Installation", "Switch Configuration", "Router Setup", "Access Points", "Network Testing", "Documentation"],
  },
  {
    id: "lan-wan",
    title: "LAN & WAN",
    category: "Networking",
    description: "Design and manage Local Area Networks and Wide Area Networks for offices and organizations.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["LAN Design", "WAN Technologies", "VLANs", "Routing", "Bandwidth Management", "Network Monitoring"],
  },
  {
    id: "wireless-networking",
    title: "Wireless Networking",
    category: "Networking",
    description: "Set up and manage wireless networks: Wi-Fi standards, security, access points, and troubleshooting.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["Wi-Fi Standards", "Security Protocols", "Access Point Setup", "Coverage Planning", "Troubleshooting", "Guest Networks"],
  },
  {
    id: "network-security",
    title: "Network Security",
    category: "Networking",
    description: "Secure networks with firewalls, VPNs, intrusion detection, access control, and security policies.",
    image_url: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400",
    topics: ["Firewalls", "VPNs", "Intrusion Detection", "Access Control", "Security Policies", "Penetration Testing"],
  },
  {
    id: "cisco-ccna",
    title: "Cisco (CCNA)",
    category: "Networking",
    description: "Prepare for Cisco CCNA certification: routing, switching, network fundamentals, and security basics.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["Routing Protocols", "Switching", "Network Fundamentals", "Security Basics", "Automation", "Exam Prep"],
  },
  {
    id: "mikrotik",
    title: "MikroTik",
    category: "Networking",
    description: "Configure and manage MikroTik routers and switches for ISPs, hotspots, and enterprise networks.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["RouterOS", "Firewall Rules", "Hotspot Setup", "QoS", "VPN Configuration", "Bandwidth Management"],
  },

  // ─── Systems & Servers (4 courses) ───
  {
    id: "windows-server",
    title: "Windows Server Administration",
    category: "Systems & Servers",
    description: "Administer Windows Server: Active Directory, Group Policy, DNS, DHCP, and server management.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["Active Directory", "Group Policy", "DNS & DHCP", "File Services", "Backup", "Monitoring"],
  },
  {
    id: "linux-admin",
    title: "Linux Administration",
    category: "Systems & Servers",
    description: "Master Linux system administration: command line, user management, services, and shell scripting.",
    image_url: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=400",
    topics: ["Command Line", "User Management", "File Systems", "Services", "Shell Scripting", "Security"],
  },
  {
    id: "virtualization",
    title: "Virtualization",
    category: "Systems & Servers",
    description: "Learn virtualization technologies: VMware, Hyper-V, containers, and virtual infrastructure management.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["VMware", "Hyper-V", "Containers", "Docker", "Virtual Networks", "Resource Management"],
  },
  {
    id: "system-maintenance",
    title: "System Maintenance",
    category: "Systems & Servers",
    description: "Maintain computer systems: updates, optimization, backup strategies, and preventive maintenance.",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    topics: ["System Updates", "Performance Optimization", "Backup Strategies", "Disk Management", "Registry", "Automation"],
  },

  // ─── Technical Support (6 courses) ───
  {
    id: "computer-troubleshooting",
    title: "Computer Troubleshooting",
    category: "Technical Support",
    description: "Diagnose and fix common computer problems: startup issues, blue screens, slow performance, and errors.",
    image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400",
    topics: ["Startup Issues", "Blue Screen Errors", "Performance Issues", "Driver Problems", "System Restore", "Diagnostic Tools"],
  },
  {
    id: "hardware-repair",
    title: "Hardware Repair & Maintenance",
    category: "Technical Support",
    description: "Repair and maintain computer hardware: motherboards, RAM, hard drives, power supplies, and peripherals.",
    image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400",
    topics: ["Motherboard Repair", "RAM & Storage", "Power Supply", "Cooling Systems", "Peripheral Setup", "Preventive Care"],
  },
  {
    id: "software-installation",
    title: "Software Installation & Repair",
    category: "Technical Support",
    description: "Install, configure, update, and troubleshoot software applications and operating systems.",
    image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400",
    topics: ["OS Installation", "Software Setup", "Updates & Patches", "Compatibility", "License Management", "Troubleshooting"],
  },
  {
    id: "printer-peripheral",
    title: "Printer & Peripheral Setup",
    category: "Technical Support",
    description: "Set up and troubleshoot printers, scanners, projectors, and other computer peripherals.",
    image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400",
    topics: ["Printer Setup", "Scanner Configuration", "Driver Installation", "Network Printing", "Troubleshooting", "Maintenance"],
  },
  {
    id: "virus-malware-removal",
    title: "Virus & Malware Removal",
    category: "Technical Support",
    description: "Detect, remove, and prevent viruses, malware, ransomware, and other security threats on computers.",
    image_url: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400",
    topics: ["Virus Detection", "Malware Removal", "Ransomware", "Antivirus Tools", "Prevention", "Safe Browsing"],
  },
  {
    id: "it-support",
    title: "IT Support / Help Desk",
    category: "Technical Support",
    description: "Provide professional IT support: ticketing systems, remote support, user training, and documentation.",
    image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400",
    topics: ["Ticketing Systems", "Remote Support", "User Training", "Documentation", "SLA Management", "Communication Skills"],
  },

  // ─── Administrative & Office Skills (7 courses) ───
  {
    id: "office-administration",
    title: "Office Administration",
    category: "Administrative & Office Skills",
    description: "Master office management: scheduling, correspondence, filing systems, and administrative procedures.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Office Management", "Scheduling", "Correspondence", "Filing Systems", "Office Equipment", "Procedures"],
  },
  {
    id: "secretarial-studies",
    title: "Secretarial Studies",
    category: "Administrative & Office Skills",
    description: "Develop professional secretarial skills: shorthand, minute-taking, scheduling, and executive assistance.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Shorthand", "Minute-Taking", "Scheduling", "Executive Assistance", "Document Preparation", "Meeting Coordination"],
  },
  {
    id: "front-desk-management",
    title: "Front Desk Management",
    category: "Administrative & Office Skills",
    description: "Manage front desk operations: visitor reception, phone handling, appointment scheduling, and professionalism.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Visitor Reception", "Phone Handling", "Appointment Scheduling", "Professionalism", "Multi-tasking", "Security Protocols"],
  },
  {
    id: "records-management",
    title: "Records Management",
    category: "Administrative & Office Skills",
    description: "Organize and manage records: filing systems, digital archives, retention policies, and compliance.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Filing Systems", "Digital Archives", "Retention Policies", "Compliance", "Database Management", "Document Control"],
  },
  {
    id: "data-entry",
    title: "Data Entry",
    category: "Administrative & Office Skills",
    description: "Build fast and accurate data entry skills: typing speed, accuracy, spreadsheets, and database input.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Typing Speed", "Accuracy", "Spreadsheet Entry", "Database Input", "Quality Control", "Productivity Tools"],
  },
  {
    id: "crm",
    title: "Customer Relationship Management (CRM)",
    category: "Administrative & Office Skills",
    description: "Use CRM tools to manage customer interactions, sales pipelines, and business relationships effectively.",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400",
    topics: ["CRM Software", "Contact Management", "Sales Pipeline", "Customer Tracking", "Reports", "Automation"],
  },
  {
    id: "professional-communication",
    title: "Professional Communication",
    category: "Administrative & Office Skills",
    description: "Develop professional communication skills: business writing, presentation, negotiation, and interpersonal skills.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Business Writing", "Presentation Skills", "Negotiation", "Interpersonal Skills", "Email Etiquette", "Public Speaking"],
  },
];

export const COURSE_CATEGORIES = ["All", ...Array.from(new Set(DLH_COURSES.map(c => c.category)))];
